version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
#    image: php:8-fpm
#    volumes:
#      - ./:/var/www
#      - ./docker/php-fpm/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php-fpm
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange_report
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data:rw

#volumes: