version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - database

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange_report
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
#      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  db-data:
